version: '3.4'

services:
  dev-proxy:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./statics:/usr/share/nginx/html:ro
     - ./cert:/etc/nginx/cert:ro
     - data/certbot/letsencrypt:/etc/letsencrypt:ro
     - data/certbot/www:/var/www/certbot
    ports:
     - "80:80"
     - "443:443"
