version: '3.4'

services:
  dev-proxy:
    image: "haproxy:lts-alpine"
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
     - ./cert/cert.crt:/etc/ssl/certs/beeline.uz_global_2023.pem:ro
    ports:
     - "443:443"
     - "80:80"
